# Generated by Django 2.0 on 2018-01-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pulpit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('third_name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('mail', models.CharField(max_length=30)),
                ('img', models.FileField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='pulpit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labapp.Pulpit'),
        ),
        migrations.AddField(
            model_name='membership',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labapp.Teacher'),
        ),
    ]
