# Generated by Django 2.0 on 2018-01-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_auto_20171224_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='img',
            new_name='imgs',
        ),
    ]
