# Generated by Django 2.0 on 2018-01-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0003_auto_20180116_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='imgs',
            new_name='img',
        ),
    ]
