# Generated by Django 2.0 on 2018-01-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0004_auto_20180116_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='img',
        ),
    ]
