# Generated by Django 2.0 on 2018-01-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0007_teacher_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulpit',
            name='zav',
            field=models.CharField(default='Неизвестный', max_length=20),
            preserve_default=False,
        ),
    ]
