# Generated by Django 2.0 on 2018-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0008_pulpit_zav'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulpit',
            name='info',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
