# Generated by Django 2.0 on 2018-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0009_pulpit_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulpit',
            name='info',
            field=models.CharField(max_length=50),
        ),
    ]
