# Generated by Django 2.0 on 2018-01-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0010_auto_20180117_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.FileField(default='img/def.jpg', upload_to='images'),
        ),
    ]
