# Generated by Django 2.0 on 2018-01-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0011_auto_20180118_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.FileField(default='images/def.jpg', upload_to='images'),
        ),
    ]
